import type { ProjectOption, RequirementRecord } from "@/modules/requirements/types";

export const requirementProjects: ProjectOption[] = [
  { id: "sap-otc-rollout", name: "S/4HANA OTC Rollout" },
  { id: "procure-global", name: "Global Procure-to-Pay Harmonization" },
  { id: "finance-close", name: "Finance Close Optimization" },
];

export const requirementRecords: RequirementRecord[] = [
  {
    id: "req-101",
    projectId: "sap-otc-rollout",
    code: "REQ-101",
    title: "Tax integration for billing",
    description: "Send billing document payload to the fiscal engine.",
    type: "Integration",
    module: "SD",
    sourceSystem: "SAP S/4",
    targetSystem: "TaxOne",
    priority: "High",
    status: "Approved",
    updatedAt: "2026-03-12T09:30:00Z",
  },
  {
    id: "req-118",
    projectId: "sap-otc-rollout",
    code: "REQ-118",
    title: "Credit block release workflow",
    description: "Control release workflow for blocked sales orders.",
    type: "Functional",
    module: "SD",
    sourceSystem: "SAP S/4",
    targetSystem: "Workflow",
    priority: "Medium",
    status: "Draft",
    updatedAt: "2026-03-11T15:40:00Z",
  },
  {
    id: "req-133",
    projectId: "sap-otc-rollout",
    code: "REQ-133",
    title: "Localized invoice output",
    description: "Generate country-specific invoice form and archive output.",
    type: "Technical",
    module: "Output",
    sourceSystem: "SAP S/4",
    targetSystem: "Adobe Forms",
    priority: "High",
    status: "Refined",
    updatedAt: "2026-03-10T14:10:00Z",
  },
  {
    id: "req-204",
    projectId: "procure-global",
    code: "REQ-204",
    title: "Supplier onboarding validations",
    description: "Validate onboarding data before vendor extension.",
    type: "Business",
    module: "MM",
    sourceSystem: "Vendor Portal",
    targetSystem: "SAP S/4",
    priority: "Critical",
    status: "Approved",
    updatedAt: "2026-03-09T11:05:00Z",
  },
  {
    id: "req-221",
    projectId: "finance-close",
    code: "REQ-221",
    title: "Closing cockpit notifications",
    description: "Notify controllers on close-task delays.",
    type: "Report",
    module: "FI",
    sourceSystem: "SAP S/4",
    targetSystem: "Teams",
    priority: "Low",
    status: "Implemented",
    updatedAt: "2026-03-08T16:55:00Z",
  },
];
